#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
##  - Указать настройки подключения к базе данных.
##  - Указать порт приложения.
##  - Настроить параметры безопасности и JWT.
##  - Включить Swagger UI.

spring:
  application:
    name: bankcards
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankcards
    hikari:
      username: postgres
      password: postgres
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#        show_sql: false
#        temp:
#          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: true
    change-log: classpath:db/migration/master.yaml
    contexts: dev